
services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
      - 5672:5672
      - 15672:15672
    restart: unless-stopped
    networks:
      - mizala
networks:
  mizala:
    name: mizala
    external: true
