version: '3.7'

services:
  nginx:
    image: nginx:alpine
    pull_policy: always
    container_name: nginx
    restart: always
    volumes:
      - ./conf.d:/etc/nginx/conf.d
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    networks:
      - mizala

networks:
  payfonte:
    name: mizala
    external: true
